name: snakemake-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9.12
  - fastqc=0.11.9
  - sra-tools=2.11.0
  - snakemake=7.18.2
  - multiqc=1.12
  - bowtie2=2.4.5
  - tbb=2020.2
  - samtools=1.15.1
  - subread=2.0.1
  - graphviz=3.0.0
  - wget=1.20.3
  - xorg-libxrender
  - xorg-libxpm
